### ISSUE TITLE
missing config.toml file?

### ISSUE THREAD

**Issue by XakV** [jeremycline/fedora-notifications#1]
Sorry to open an issue for this, but what is this task in the dev role trying to do?

```
    name: Install application configuration
    become_user: "{{ ansible_env.SUDO_USER }}"
    copy: src=config.toml dest=/home/{{ ansible_env.SUDO_USER }}/config.toml
```

I can't find that config file in this repo. Is it something I'm supposed to create?

Thanks!

**Comment by jeremycline** [comment]
It copies the base configuration from ``devel/ansible/roles/dev/files/`` to the user's home directory. Later a systemd unit is set up that points an environment variable at it so the developer can easily fiddle with application settings.

By default ``copy`` looks in that role's ``files`` directory for the source file.

**Comment by jeremycline** [comment]
Ah, I see, it's getting caught up in a gitignore file. Sorry about that.

**Comment by XakV** [comment]
:) Thanks - wanted to make sure I wasnt missing something.
